class TaskNotFoundError(Exception):
    """Задача не найдена."""
    pass

class TaskValidationError(Exception):
    """Ошибка валидации задачи."""
    pass
